### ISSUE TITLE
failed to load rcdk

### ISSUE THREAD

**Issue by fdq09eca** [CDK-R/cdkr#121]
I am on a M1 BigSur. I have no problem in loading`rJava` but it seems `rcdklibs` has not been load properly when I load `rcdk`.
```r
> library("rJava")
> library("rcdk")
Loading required package: rcdklibs
zsh: trace trap  R
```

Here is my java version
```
chrislam@ChrisLams-MBP ~ % java -version 
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)
```

**Comment by rajarshi** [comment]
Unfortunately, I don't have access to an M1 setup to test this on.

Are you using the latest code from Github?

**Comment by tsufz** [comment]
Hi @rajarshi, I can reproduce this error on a Windows 10 with current R-Studio running (same on Windows Server 2019). The error is not reproducible in the native R-GUI and thus maybe related to any interaction with R-Studio.

I run the latest versions of rcdk and rcdklibs installed from GitHub.

** Screenshots **
![2022-06-25 09_14_17-Window](https://user-images.githubusercontent.com/2526819/175763820-030b51a4-ddf7-4cb5-93fc-f2022736a833.png)
![2022-06-25 09_13_48-Window](https://user-images.githubusercontent.com/2526819/175763822-822a9358-8768-481a-bf38-5b0e486664f0.png)

**System (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu] Windows 10 21H2 / but reproducible on Windows Server 2019
 - Java Version: openjdk version "11.0.13" 2021-10-19
 - R Version: 4.2.0

> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0   

**Additional context**
Add any other context about the problem here.

Best
Tobias

**Comment by tsufz** [comment]
I dug a little deeper. There is obviously a rJava / RStudio bug in R4.20. A patch for Windows is available. See https://community.rstudio.com/t/problems-with-rjava-in-rstudio/135896.
