### ISSUE TITLE
parse.smiles doesn't stop or give warnings for invalid SMILES

### ISSUE THREAD

**Issue by adelenelai** [CDK-R/cdkr#76]
I ran parse.smiles on a long list (14,000+) of SMILES, some of which I later discovered were actually invalid. However, the function doesn't stop or give warnings as I'd have expected, and it took a while to trace which SMILES were problematic (so that I can remove/fix them).

Small snippet to reproduce:

```R
smi <- c('CCC', 'c1ccccc1',  'N/A', 'C(C)(C=O)C(CCNC)C1CC1C(=O)', 'foo')
parse.smiles(smi)
```

Output:

```
$CCC
[1] "Java-Object{AtomContainer(171493374, #A:3, Atom(1876682596, S:C, H:3, AtomType(1876682596, FC:0, ..."

$c1ccccc1
[1] "Java-Object{AtomContainer(806511723, #A:6, Atom(1250442005, S:C, H:1, AtomType(1250442005, FC:0, ..."

$`N/A`
NULL

$`C(C)(C=O)C(CCNC)C1CC1C(=O)`
[1] "Java-Object{AtomContainer(2032079962, #A:14, Atom(953082513, S:C, H:1, AtomType(953082513, FC:0..."

$foo
NULL
```

**Comment by bachi55** [comment]
Hei,

I looked at your code and would suggest to just throw a warning and not modify the output, e.g. by removing SMILES that cannot be parsed. To find out which SMILES could not be parsed you could just do something like this:

```
smi <- c('CCC', 'c1ccccc1',  'N/A', 'C(C)(C=O)C(CCNC)C1CC1C(=O)', 'foo')
res <- parse.smiles(smi)

smi[sapply(res, is.null)]
# or 
which(sapply(res, is.null))
``` 
Output:
```
[1] "N/A" "foo"
# or
N/A foo 
  3   5 
```
BR, Eric

**Comment by adelenelai** [comment]
Thanks for your feedback Eric. 

Clarification: unparseable SMILES from the original list of input SMILES are not removed, rather, NULLS (which result from those SMILES being unparseable) would be removed from the output if desired.

Do you have use cases where modifying the output in this way would be problematic? 

In any case, the default for omit.nulls = FALSE, so it's merely giving the user the option. Having it built-in saves extra lines of code to identify (as you suggested) then remove them.

**Comment by bachi55** [comment]
Hei, 

in my experience it is very important that the order in which I input elements into a function, should be the one they leave the function (exclude sorting functions here ;)). So that removing the elements would violate this. I argue here from the point of view of someone that usually processes small (<1000) molecules and wants to exactly know, where things went wrong, e.g. unparseable SMILES.

However, as you tell if the default would stay like this, i.e. keeping all the elements, and the user explicitly has to say ```omit.nulls=TRUE``` it should be fine. 

BR, Eric
